version: '3.8'
services:
  client:
    container_name: client
    build: ./frontend
    ports:
      - 3001:3000 # route it out of 3000 so it doesn't compete againt frontend
    working_dir: /app
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    hostname: client
    depends_on:
      - match1
      - match2
    command: npm run dev
  match1:
    container_name: match1
    build: ./match
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./match:/app/
    environment:
      #- environment=cheap
      - environment=local
      - PORT=5000
      - DB_USER=postgres_user
      - DB_HOST=postgres_service
      - DB_PASS=postgres_password
      - DB_PORT=5432
      - DB_NAME=postgres_user # default db name if not set
      - DB_RETRY_BACKOFF=1
      - ORIGIN_LOCAL=http://localhost:3000
      - ORIGIN_REMOTE=https://virtualavatar.trip1elift.com
      - AISLE_KEY=passcode
      - SELF_IP=match1:5000
    depends_on:
      - postgres_service
    tty: true
    command: nodemon --exec 'go run main.go | echo "crashed"' --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
  match2:
    container_name: match2
    build: ./match
    ports:
      - 5001:5000
    working_dir: /app
    volumes:
      - ./match:/app/
    environment:
      #- environment=cheap
      - environment=local
      - PORT=5000
      - DB_USER=postgres_user
      - DB_HOST=postgres_service
      - DB_PASS=postgres_password
      - DB_PORT=5432
      - DB_NAME=postgres_user # default db name if not set
      - DB_RETRY_BACKOFF=1
      - ORIGIN_LOCAL=http://localhost:3000
      - ORIGIN_REMOTE=https://virtualavatar.trip1elift.com
      - AISLE_KEY=passcode
      - SELF_IP=match2:5000
    depends_on:
      - postgres_service
    tty: true
    command: nodemon --exec 'go run main.go | echo "crashed"' --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
  postgres_service:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      # let backend to populate the database
      # - ./match/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres:
    driver: local