version: '3.8'
services:
  client:
    container_name: client
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    hostname: client
    depends_on:
      - match
    command: npm run dev
  match:
    container_name: match
    build: ./match
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./match:/app/
    environment:
      - DB_USER=postgres_user
      - DB_HOST=postgres_container
      - DB_PASS=postgres_password
      - DB_PORT=5432
      - ORIGIN=http://localhost:3000
      - AISLE_KEY=passcode
      - SIBILING_IP=172.16.238.12
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    depends_on:
      - postgres
    tty: true
    command: nodemon --exec 'go run main.go | echo "crashed"' --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
  match2:
    container_name: match2
    build: ./match
    ports:
      - 5001:5000
    working_dir: /app
    volumes:
      - ./match:/app/
    environment:
      - DB_USER=postgres_user
      - DB_HOST=postgres_container
      - DB_PASS=postgres_password
      - DB_PORT=5432
      - ORIGIN=http://localhost:3000
      - AISLE_KEY=passcode
      - SIBILING_IP=172.16.238.11
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    depends_on:
      - postgres
    tty: true
    command: nodemon --exec 'go run main.go | echo "crashed"' --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
  postgres:
    container_name: postgres_container
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres:
    driver: local
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"