version: '3.8'
services:
  stream:
    container_name: stream
    build: ./stream
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ./stream:/app/
    # override cmd
    command: [ "nodemon", "--exec", "go", "run", "main.go", "--signal", "SIGTERM", "--legacy-watch", "--ext", ".go,.mod,.sum" ]
  match:
    container_name: match
    build: ./match
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./match:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    command: sh -c "sudo sam build && sudo sam local start-api --port 8080 --host 0.0.0.0 --container-host host.docker.internal"